### ISSUE TITLE
按照READ.ME运行该项目，遇到的Error

### ISSUE THREAD

**Issue by wrb233** [seisman/how-to-write-makefile#17]
wl (master) how-to-write-makefile
$ e:/general/Firefox/firefox build/html/index.html&
[1] 7800
wl (master) how-to-write-makefile
$ make latexpdf
Running Sphinx v2.0.1
loading translations [zh_CN]... done
making output directory... done
loading pickled environment... done
WARNING: no Babel option known for language 'zh_CN'
building [mo]: targets for 0 po files that are out of date
building [latex]: all documents
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
processing Makefile.tex... index overview introduction rules recipes variables c                                          onditionals functions invoke implicit_rules archives postscript
resolving references...
done
writing... WARNING: no Babel option known for language 'zh_CN'
done
copying TeX support files... copying TeX support files...
done
build succeeded, 2 warnings.

The LaTeX files are in build\latex.
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'xelatex    -recorder  "Makefile.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/W32TeX) (preloaded                                           format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./Makefile.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 6 language(s) loaded.
(./sphinxmanual.cls
Document Class: sphinxmanual 2018/12/23 v2.0 Document class (Sphinx manual)
(c:/texlive/2017/texmf-dist/tex/latex/base/report.cls
Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
(c:/texlive/2017/texmf-dist/tex/latex/base/size10.clo)))
(c:/texlive/2017/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(c:/texlive/2017/texmf-dist/tex/latex/amsmath/amstext.sty
(c:/texlive/2017/texmf-dist/tex/latex/amsmath/amsgen.sty))
(c:/texlive/2017/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(c:/texlive/2017/texmf-dist/tex/latex/amsmath/amsopn.sty))
(c:/texlive/2017/texmf-dist/tex/latex/amsfonts/amssymb.sty
(c:/texlive/2017/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(c:/texlive/2017/texmf-dist/tex/generic/babel/babel.sty
(c:/texlive/2017/texmf-dist/tex/generic/babel-english/english.ldf
(c:/texlive/2017/texmf-dist/tex/generic/babel/babel.def
(c:/texlive/2017/texmf-dist/tex/generic/babel/xebabel.def))))
! Undefined control sequence.
l.21 \setmainfont
                 {FreeSerif}[
?

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.21 \setmainfont{F
                   reeSerif}[
?
! Undefined control sequence.
l.28 \setsansfont
                 {FreeSans}[
?
! Undefined control sequence.
l.35 \setmonofont
                 {FreeMono}[
?
(c:/texlive/2017/texmf-dist/tex/latex/fncychap/fncychap.sty) (./sphinx.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/ltxcmds.sty)
(c:/texlive/2017/texmf-dist/tex/latex/graphics/graphicx.sty
(c:/texlive/2017/texmf-dist/tex/latex/graphics/keyval.sty)
(c:/texlive/2017/texmf-dist/tex/latex/graphics/graphics.sty
(c:/texlive/2017/texmf-dist/tex/latex/graphics/trig.sty)
(c:/texlive/2017/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(c:/texlive/2017/texmf-dist/tex/latex/graphics-def/xetex.def)))
(c:/texlive/2017/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(c:/texlive/2017/texmf-dist/tex/latex/base/textcomp.sty
(c:/texlive/2017/texmf-dist/tex/latex/base/ts1enc.def))
(c:/texlive/2017/texmf-dist/tex/latex/titlesec/titlesec.sty)
(c:/texlive/2017/texmf-dist/tex/latex/tabulary/tabulary.sty
(c:/texlive/2017/texmf-dist/tex/latex/tools/array.sty))
(c:/texlive/2017/texmf-dist/tex/latex/tools/longtable.sty)
(c:/texlive/2017/texmf-dist/tex/latex/varwidth/varwidth.sty)
(./sphinxmulticell.sty) (c:/texlive/2017/texmf-dist/tex/latex/base/makeidx.sty)
 (c:/texlive/2017/texmf-dist/tex/latex/framed/framed.sty)
(c:/texlive/2017/texmf-dist/tex/latex/xcolor/xcolor.sty
(c:/texlive/2017/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(c:/texlive/2017/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix
<2008/02/07> (tvz)) (./footnotehyper-sphinx.sty)
(c:/texlive/2017/texmf-dist/tex/latex/float/float.sty)
(c:/texlive/2017/texmf-dist/tex/latex/wrapfig/wrapfig.sty)
(c:/texlive/2017/texmf-dist/tex/latex/parskip/parskip.sty)
(c:/texlive/2017/texmf-dist/tex/latex/base/alltt.sty)
(c:/texlive/2017/texmf-dist/tex/latex/upquote/upquote.sty)
(c:/texlive/2017/texmf-dist/tex/latex/capt-of/capt-of.sty)
(c:/texlive/2017/texmf-dist/tex/latex/needspace/needspace.sty)
(c:/texlive/2017/texmf-dist/tex/latex/carlisle/remreset.sty)
(./sphinxhighlight.sty)
(c:/texlive/2017/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/ifluatex.sty)))))
(c:/texlive/2017/texmf-dist/tex/latex/geometry/geometry.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(c:/texlive/2017/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(c:/texlive/2017/texmf-dist/tex/latex/hyperref/hyperref.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(c:/texlive/2017/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(c:/texlive/2017/texmf-dist/tex/latex/hyperref/pd1enc.def)
(c:/texlive/2017/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(c:/texlive/2017/texmf-dist/tex/latex/hyperref/puenc.def)
(c:/texlive/2017/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hxetex.

(c:/texlive/2017/texmf-dist/tex/latex/hyperref/hxetex.def
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(c:/texlive/2017/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(c:/texlive/2017/texmf-dist/tex/latex/oberdiek/hypcap.sty)
(./sphinxmessages.sty) (c:/texlive/2017/texmf-dist/tex/latex/ctex/ctex.sty
(c:/texlive/2017/texmf-dist/tex/latex/l3kernel/expl3.sty
(c:/texlive/2017/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(c:/texlive/2017/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))
(c:/texlive/2017/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(c:/texlive/2017/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(c:/texlive/2017/texmf-dist/tex/latex/ctex/ctexhook.sty)
(c:/texlive/2017/texmf-dist/tex/latex/ctex/ctexpatch.sty)
(c:/texlive/2017/texmf-dist/tex/latex/base/fix-cm.sty
(c:/texlive/2017/texmf-dist/tex/latex/base/ts1enc.def))
(c:/texlive/2017/texmf-dist/tex/latex/ms/everysel.sty)
(c:/texlive/2017/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(c:/texlive/2017/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(c:/texlive/2017/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(c:/texlive/2017/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(c:/texlive/2017/texmf-dist/tex/latex/fontspec/fontspec.sty
(c:/texlive/2017/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(c:/texlive/2017/texmf-dist/tex/latex/base/fontenc.sty
(c:/texlive/2017/texmf-dist/tex/latex/base/tuenc.def))
(c:/texlive/2017/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(c:/texlive/2017/texmf-dist/tex/xelatex/xecjk/xunicode-addon.sty
(c:/texlive/2017/texmf-dist/tex/xelatex/xunicode/xunicode.sty
(c:/texlive/2017/texmf-dist/tex/latex/tipa/t3enc.def)))
(c:/texlive/2017/texmf-dist/tex/xelatex/xunicode/xunicode.sty
*** Reloading Xunicode for encoding 'TU' ***
) (c:/texlive/2017/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def)
(c:/texlive/2017/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(c:/texlive/2017/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty
(c:/texlive/2017/texmf-dist/tex/generic/ulem/ulem.sty)
(c:/texlive/2017/texmf-dist/tex/latex/environ/environ.sty
(c:/texlive/2017/texmf-dist/tex/latex/trimspaces/trimspaces.sty))
(c:/texlive/2017/texmf-dist/tex/latex/cjk/texinput/CJKfntef.sty)))
(c:/texlive/2017/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(c:/texlive/2017/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg))
(c:/texlive/2017/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-chinese.def
(c:/texlive/2017/texmf-dist/tex/latex/ctex/config/ctex-name-utf8.cfg))
(c:/texlive/2017/texmf-dist/tex/latex/tools/indentfirst.sty)
(c:/texlive/2017/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windows.def
(c:/texlive/2017/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-windowsnew.def)
)) (c:/texlive/2017/texmf-dist/tex/latex/ctex/config/ctex.cfg)
Writing index file Makefile.idx
(./Makefile.aux) (c:/texlive/2017/texmf-dist/tex/latex/tipa/t3cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
(c:/texlive/2017/texmf-dist/tex/latex/hyperref/nameref.sty
(c:/texlive/2017/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))

Package hyperref Warning: Rerun to get /PageLabels entry.

ABD: EverySelectfont initializing macros [1]
(c:/texlive/2017/texmf-dist/tex/latex/amsfonts/umsa.fd)
(c:/texlive/2017/texmf-dist/tex/latex/amsfonts/umsb.fd) [1] [2] [1] [2]
Chapter 1.
[1] [2]
Chapter 2.
[3] [4] [5] [6] [7] [8]
Underfull \hbox (badness 10000) in paragraph at lines 497--502
[]\TU/SimSun(0)/m/n/10 默 认 的 情 况 下，| \TU/lmtt/m/n/10 make \TU/SimSun(0)/m                                          /n/10
命 令 会 在 当 前 目 录 下 按 顺 序 找 寻 文 件 名 为  |“\TU/lmtt/m/n/10 GNUmake                                          file\TU/SimSun(0)
/m/n/10 ” 、|
[9] [10]
Chapter 3.

LaTeX Font Warning: Font shape `TU/FangSong(0)/m/it' undefined
(Font)              using `TU/FangSong(0)/m/n' instead on input line 629.

[11] [12] [13] [14] [15] [16]
Underfull \hbox (badness 10000) in paragraph at lines 954--959
[]\TU/SimSun(0)/m/n/10 这 样 描 述 这 三 个 东 西，|  可 能 还 是 没 有 说 清 楚                                          ，|  还 是 举 个 例 子 来
说 明 一 下 吧。|  如 果 我 们 的

Underfull \hbox (badness 8056) in paragraph at lines 954--959
\TU/lmtt/m/n/10 <target-parrtern> \TU/SimSun(0)/m/n/10 定 义 成 \TU/lmtt/m/n/10                                           %.
o \TU/SimSun(0)/m/n/10 ，|  意 思 是 我 们 的 \TU/lmtt/m/n/10 <target>; \TU/SimS                                          un(0)/
m/n/10 集 合 中 都 是 以 \TU/lmtt/m/n/10 .o \TU/SimSun(0)/m/n/10 结 尾 的，|  而                                           如 果
[17] [18] [19] [20]
Chapter 4.
[21] [22] [23]
Underfull \hbox (badness 10000) in paragraph at lines 1295--1297
[]\TU/SimSun(0)/m/n/10 但 是 \TU/lmtt/m/n/10 make \TU/SimSun(0)/m/n/10 命 令 中                                           的 有
几 个 参 数 并 不 往 下 传 递，|  它 们 是 \TU/lmtt/m/n/10 -C , -f , -h, -o \TU/                                          SimSun(0)/m/n
/10 和 \TU/lmtt/m/n/10 -W  |\TU/SimSun(0)/m/n/10 （有 关

Underfull \hbox (badness 10000) in paragraph at lines 1321--1323
[]\TU/SimSun(0)/m/n/10 当 你 使 用 \TU/lmtt/m/n/10 -C \TU/SimSun(0)/m/n/10 参 数                                           来 指
定 \TU/lmtt/m/n/10 make \TU/SimSun(0)/m/n/10 下 层 \TU/lmtt/m/n/10 Makefile \TU/                                          Si
mSun(0)/m/n/10 时，| \TU/lmtt/m/n/10 -w \TU/SimSun(0)/m/n/10 会 被 自 动 打 开                                           的。|  如 果
 参 数 中 有 \TU/lmtt/m/n/10 -s
[24] [25] [26]
Chapter 5.
[27] [28] [29] [30] [31] [32] [33] [34] [35] [36]
Chapter 6.
[37] [38] [39] [40]
Chapter 7.
[41]
Underfull \hbox (badness 10000) in paragraph at lines 2112--2117
\TU/lmtt/m/n/10 ) \TU/SimSun(0)/m/n/10 相 当 于 \TU/lmtt/m/n/10 $(patsubst <patt                                          er
n>,<replacement>,$(var)) \TU/SimSun(0)/m/n/10 ，|  而 \TU/lmtt/m/n/10 $(var:
[42] [43] [44]
Underfull \hbox (badness 10000) in paragraph at lines 2377--2380
[]\TU/SimSun(0)/m/n/10 如 果 我 们 的 \TU/lmtt/m/n/10 $(VPATH) \TU/SimSun(0)/m/n                                          /10
值 是 \TU/lmtt/m/n/10 src:../headers \TU/SimSun(0)/m/n/10 ，|  那 么 \TU/lmtt/m/                                          n/10
 $(patsubst %,-I%,$(subst :, ,
[45] [46] [47] [48]
Underfull \hbox (badness 10000) in paragraph at lines 2640--2642
[]\TU/lmtt/m/n/10 $ \TU/SimSun(0)/m/n/10 字 符。|
[49] [50] [51] [52]
Chapter 8.

Underfull \hbox (badness 10000) in paragraph at lines 2766--2768
[]\TU/SimSun(0)/m/n/10 前 面 我 们 说 过，| \TU/lmtt/m/n/10 GNU make \TU/SimSun(                                          0)/m/n
/10 找 寻 默 认 的 \TU/lmtt/m/n/10 Makefile \TU/SimSun(0)/m/n/10 的 规 则 是 在                                           当 前 目 录 下
 依 次 找 三 个 文 件
[53] [54]

LaTeX Font Warning: Font shape `TU/lmtt/bx/it' in size <10> not available
(Font)              Font shape `TU/lmtt/b/sl' tried instead on input line 2892.

[55] [56]
Underfull \hbox (badness 10000) in paragraph at lines 2991--2994
[]\TU/SimSun(0)/m/n/10 假 定 目 标 \TU/lmtt/m/n/10 <file>;
[57] [58]
Chapter 9.
[59]
Underfull \hbox (badness 10000) in paragraph at lines 3072--3078
\TU/lmtt/m/n/10 .f, .F, .r, .y, .l, .s, .S, .mod, .sym, .def, .h, .info, .dvi,
.tex, .texinfo, .texi,
[60] [61]
Underfull \hbox (badness 10000) in paragraph at lines 3190--3192
[]\TU/lmtt/m/n/10 <n>.ln  |\TU/SimSun(0)/m/n/10 （\TU/lmtt/m/n/10 lint \TU/SimSu
n(0)/m/n/10 生 成 的 文 件）|  的 依 赖 文 件 被 自 动 推 导 为 \TU/lmtt/m/n/10                                           n.c \TU/SimSun(0
)/m/n/10 ，|  其 生 成 命 令 是：| \TU/lmtt/m/n/10 $(LINT)
[62] [63] [64]
Underfull \hbox (badness 5832) in paragraph at lines 3406--3413
[]\TU/SimSun(0)/m/n/10 这 条 规 则 告 诉 \TU/lmtt/m/n/10 make \TU/SimSun(0)/m/n/                                          10 把
所 有 的 \TU/lmtt/m/n/10 .y \TU/SimSun(0)/m/n/10 文 件 都 以 \TU/lmtt/m/n/10 bis                                          on -d
<n>.y \TU/SimSun(0)/m/n/10 执 行，|  然 后 生 成 \TU/lmtt/m/n/10 <n>.tab.c \TU/S                                          imSun(
0)/m/n/10 和
[65] [66] [67] [68] [69] [70]
Chapter 10.
[71] [72]
Chapter 11.
[73]
No file Makefile.ind.
[74] (./Makefile.aux)

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

 )
Output written on Makefile.pdf (79 pages).
Transcript written on Makefile.log.
Latexmk: Index file 'Makefile.idx' was written
Latexmk: References changed.
===========Latexmk: Missing input file: 'Makefile.ind' from line
  'No file Makefile.ind.'
Latexmk: Missing input file: 'Makefile.ind' from line
  'No file Makefile.ind.'
Latexmk: References changed.
Latexmk: Log file says output to 'Makefile.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'Makefile.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
=== TeX engine is 'XeTeX'
Latexmk: Errors, so I did not complete making targets
C:\texlive\2017\bin\win32\runscript.tlu:708: command failed with exit code 12:
perl.exe c:\texlive\2017\texmf-dist\scripts\latexmk\latexmk.pl -pdf -dvi- -ps-                                            Makefile.tex
wl (master) how-to-write-makefile
$

**Comment by seisman** [comment]
Fixed now. Please try again.
