### ISSUE TITLE
每行80字符的显示问题

### ISSUE THREAD

**Issue by madjxatw** [seisman/how-to-write-makefile#22]
有断行的话，在 HTML 中上下两行拼接时浏览器会自动添加一个空格，对于英文没有问题，但是对于中文来说，太多的空格会影响视觉效果（个人感觉，或许别人不介意？）。

关于续行特性，在 [CSS Text Module Level 3](https://drafts.csswg.org/css-text-3/#line-break-transform) 草案中已经有规范，软断行（soft linebreak）处并合时应视前后字符所属语系而酌情添加空格，较新版本的 Firefox 已经实现了这一特性，而 Chrome 依然不支持。

在 RST 中，可以在行结尾处使用 ``\`` 来表示续行，这样行合并时就不会出现空格，但是这给编辑带来了很大的不便。我基本不写中文的 RST 文档，如果写的话，也不会强制断行。

**Comment by seisman** [comment]
这是中文文档的通病，目前不知道有什么好的解决办法。强制换行的主要原因在于如果把一整段中文写在一行里，PR review的时候会比较困难。

我之前写了个sphinx插件来处理中文空格问题，在 #23 里我把这个插件加进去了，你可以自己编译HTML文档试试看效果。

**Comment by madjxatw** [comment]
试了一下 sphinx-cjkspace 插件，问题解决，暂时没有碰到问题。

中文软换行问题，还是要靠浏览器来解决，我记得有人给 Chromium 项目提出 feature request 要求实现换行转换特性，至今没有实现, sigh...
