### ISSUE TITLE
addprefix的功能解释存在错误

### ISSUE THREAD

**Issue by CHICKis** [seisman/how-to-write-makefile#27]
正确解释应该是：
$(addprefix <prefix>,<names...>)
- 名称：加前缀函数——addprefix。
- 功能：把前缀 <prefix> 加到 <names> 中的每个单词**_前面_**。
- 返回：返回加过前缀的文件名序列。
- 示例：$(addprefix src/,foo bar) 返回值是 src/foo src/bar 。

**Comment by seisman** [comment]
有时间的话请发一个 pull request.

**Comment by seisman** [comment]
Closed by #28
