### ISSUE TITLE
pdf 下载链接挂掉了

### ISSUE THREAD

**Issue by StudentWeis** [seisman/how-to-write-makefile#32]
大佬你好，README 中的 pdf 下载链接挂掉了。

如下：

PDF下载： https://seisman.github.io/how-to-write-makefile/Makefile.pdf

**Comment by seisman** [comment]
PDF的自动生成目前存在问题 暂时没有办法

**Comment by StudentWeis** [comment]
> PDF的自动生成目前存在问题 暂时没有办法

好吧

**Comment by chunyexixiaoyu** [comment]
> PDF的自动生成目前存在问题 暂时没有办法
能否自动上传一个版本呢

**Comment by seisman** [comment]
已修复，PDF 目前已经可以下载了
