### ISSUE TITLE
隐含规则-隐含规则一览 有错误

### ISSUE THREAD

**Issue by yifanlu0227** [seisman/how-to-write-makefile#36]
https://seisman.github.io/how-to-write-makefile/implicit_rules.html#id3

2. 编译C++程序的隐含规则。

n.o 的目标的依赖目标会自动推导为 n.cc, n.cpp, or n.C ，并且其生成命令是 $(CXX) –c  $(CPPFLAGS) **$(CFLAGS)** 。（建议使用 .cc 作为C++源文件的后缀，而不是 .C ）

应该为 **$(CXXFLAGS)**

**Comment by seisman** [comment]
Fixed by 3d933d45a115da4ef1d1fb5caddbf3d4386282aa.
