### ISSUE TITLE
隐含规则->定义模式规则->模式规则介绍 第二段有误

### ISSUE THREAD

**Issue by lewis1573** [seisman/how-to-write-makefile#46]
“如果 % 定义在目标中，那么，目标中的 % 的值决定了依赖目标中的 % 的值，也就是说，目标中的模式的 % 决定了依赖目标中 % 的样子。”
这一段应该写反了，应该是
“如果 % 定义在目标中，那么，依赖中的 % 的值决定了目标中的 % 的值，也就是说，依赖中的模式的 % 决定了目标中 % 的样子。”

**Comment by seisman** [comment]
Closed by https://github.com/seisman/how-to-write-makefile/pull/47.
