### ISSUE TITLE
期待后续的改进

### ISSUE THREAD

**Issue by gokucai** [seisman/how-to-write-makefile#50]
如题，很多地方语句不通顺。语法错误太多以至于影响阅读效率，好多地方要反复读几遍才能搞清楚作者想表达什么。
在隐含规则搜索算法那一篇貌似与标准文档有出入。
不过还是要感谢作者，起码一个精简版的中文手册不用花很多时间也可以快速入门。

**Comment by seisman** [comment]
我几乎已经不再使用 Makefile，所以没有动力对手册进行改进。你在阅读的过程中发现问题可以发 PR 来帮助改进。
