### ISSUE TITLE
在阅读一个项目的makefile时遇到的问题

### ISSUE THREAD

**Issue by cgl-sd** [seisman/how-to-write-makefile#54]
作者你好，我最近在看一个项目的makefile，有一些不明白的，希望借此平台请教一下你。
`$(MAKE) $(MFLAGS) "OBJ = $(OBJ)" "INC = $(INC)" "EXE = ../$(EXE)" ../$(EXE)
`

这是一个makefile的命令部分，引号""部分是传递参数，我想请问以下引号后面的../$(EXE)是什么意思

**Comment by tgxpl** [comment]
../代表上级目录，$(EXE)代表EXE变量的内容。假如上级目录是include，EXE存的内容是aaa，那么../$(EXE)代表的就是include/aaa

**Comment by cgl-sd** [comment]
非常感谢，我看了下makefile，明白了
